version: '3.7'

services:
  app_gl:
    build: .
    container_name: app_gl
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /code
    command: flask run --host=0.0.0.0
    networks:
      - gestaolegal

  db_gl:
    environment:
      MYSQL_DATABASE: gestaolegal