services:
  app_gl:
    build: .
    image: gestao_legal_app
    container_name: app_gl
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /code
    networks:
      - gestaolegal
    restart: unless-stopped

  db_gl:
    image: mysql:latest
    container_name: db_gl
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_USER: gestaolegal
      MYSQL_PASSWORD: gestaolegal
      MYSQL_DATABASE: gestaolegal
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gestaolegal

  adminer_gl:
    image: adminer
    container_name: adminer_gl
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - gestaolegal

networks:
  gestaolegal:

volumes:
  mysql_data:
    driver: local
