version: '3.7'

services:
  adminer_gl:
    image: adminer
    container_name: adminer_gl
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - gestaolegal

networks:
  gestaolegal:
    name: gestaolegal
