version: '3.7'

services:
  app_gl_test:
    build: .
    image: gestao_legal_app
    container_name: app_gl
    ports:
      - "5001:5000"
    volumes:
      - type: bind
        source: .
        target: /code
    networks:
      - gestaolegal
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    command: gunicorn --bind 0.0.0.0:5000 --workers=4 --timeout=300 wsgi:app