# https://hub.docker.com/_/mysql
version: '3.7'

services:
  gl_app:
    build: .
    container_name: gl_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /code
    command: [ "python", "./app.py"]

  gl_db:
    image: mysql
    container_name: gl_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_DATABASE: gestaolegal
      MYSQL_USER: gestaolegal
      MYSQL_PASSWORD: gestaolegal
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - type: bind
        source: /opt/docker_volumes/mysql_data
        target: /var/lib/mysql

  gl_adminer:
    image: adminer
    container_name: gl_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"