name: Deploy to QA VPS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to QA'
        required: true
        default: main
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd gestaolegal
            git checkout ${{ github.event.inputs.branch }}
            git pull

            export ENV=qa
            make up
            make init_dev_enviroment


